USE [master]
GO
/****** Object:  Database [cobeca]    Script Date: 16/03/2022 14:03:01 ******/
CREATE DATABASE [cobeca]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'cobeca', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\cobeca.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'cobeca_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\cobeca_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [cobeca] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [cobeca].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [cobeca] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [cobeca] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [cobeca] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [cobeca] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [cobeca] SET ARITHABORT OFF 
GO
ALTER DATABASE [cobeca] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [cobeca] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [cobeca] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [cobeca] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [cobeca] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [cobeca] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [cobeca] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [cobeca] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [cobeca] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [cobeca] SET  DISABLE_BROKER 
GO
ALTER DATABASE [cobeca] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [cobeca] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [cobeca] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [cobeca] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [cobeca] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [cobeca] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [cobeca] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [cobeca] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [cobeca] SET  MULTI_USER 
GO
ALTER DATABASE [cobeca] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [cobeca] SET DB_CHAINING OFF 
GO
ALTER DATABASE [cobeca] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [cobeca] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [cobeca] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [cobeca] SET QUERY_STORE = OFF
GO
USE [cobeca]
GO
/****** Object:  Table [dbo].[inscripcion]    Script Date: 16/03/2022 14:03:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[inscripcion](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](20) NULL,
	[Apellido] [nvarchar](20) NULL,
	[Identificacion] [int] NULL,
	[Edad] [int] NULL,
	[Casa] [nvarchar](10) NULL,
 CONSTRAINT [PK_inscripcion] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[inscripcion] ON 
GO
INSERT [dbo].[inscripcion] ([id], [Nombre], [Apellido], [Identificacion], [Edad], [Casa]) VALUES (1, N'Jose', N'Padilla', 19907954, 31, N'Hogwarts')
GO
SET IDENTITY_INSERT [dbo].[inscripcion] OFF
GO
USE [master]
GO
ALTER DATABASE [cobeca] SET  READ_WRITE 
GO
